database:
  server: 127.0.0.1
  name: linky
  user: linky
  password: mypassword
influx_db:
  server: 127.0.0.1
  port: 8086
  name: linky
device: /dev/ttyS0
use_utc: True
period: 30
# DEBUG | INFO | WARNING | ERROR | CRITICAL
logLevel: DEBUG
led_gpio_pin: 26